# 第1天：

## 下面这段代码输出的内容

```go
package main

import (
	"fmt"
)

func main() {
  defer func() { fmt.Println("打印前") }()
  defer func() { fmt.Println("打印中") }()
  defer func() { fmt.Println("打印后") }()

  panic("触发异常")
}
```

## 答案：
打印后
打印中
打印前
panic: 触发异常

## 解析：

具体来说，这个函数包含了三个`defer`语句，每个`defer`语句都包含一个匿名函数，这些匿名函数在main函数执行完毕后会按照后进先出（LIFO）的顺序执行，即最后一个defer语句中的匿名函数会最先执行，然后是第二个defer语句中的匿名函数，最后是第一个defer语句中的匿名函数。

在main函数的最后，调用了panic函数并传入了一个字符串"触发异常"，这会导致程序立即停止执行，并开始执行defer语句中的匿名函数。因此，这个函数的执行顺序如下：

1.panic函数被调用，程序开始执行defer语句中的匿名函数。
2.第三个defer语句中的匿名函数被执行，打印"打印后"。
3.第二个defer语句中的匿名函数被执行，打印"打印中"。
4.第一个defer语句中的匿名函数被执行，打印"打印前"。
5.程序终止，并输出panic信息"触发异常"。

这里还涉及一个比较细节的知识点：当 panic 函数被调用时，程序会立即停止正常的执行流程，并开始执行所有已经注册的 defer 语句。因此，尽管 panic 函数中传入了"触发异常"的字符串，这个信息并不会立即打印出来。
